package com.com.poke.search.compute;

import com.com.poke.search.context.ParentsContext;
import com.com.poke.search.context.TrainerContext;
import com.com.rng.mt.MTRng;

/**
 * Calculates the {@link OffspringSpread} element, {@code T}, from the specified {@code contexts}.
 *
 * @param <T> The {@code Type} of the {@code SpreadElement} which this {@code Calculator} can {@link
 *            #calculate(ParentsContext, TrainerContext, MTRng)}.
 */
interface SearchElementCalculator<T> {

    /**
     * Calculates the {@code SpreadElement} ({@code T}) from the given {@code contexts}.
     *
     * @param parentsContext The {@link ParentsContext} specifying details of the parent {@code Pokémon}.
     * @param trainerContext The {@link TrainerContext} specifying details of the trainer (breeder).
     * @param rng            The {@link MTRng} (in required state) to be used in computation.
     * @return The {@code SpreadElement} generated by the provided {@code rng}, under the given {@code contexts}.
     */
    T calculate(ParentsContext parentsContext, TrainerContext trainerContext, MTRng rng);
}
